# Site settings
title: "Chris Pauley's Resume on GitHub"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Chris Pauley"
resume_title:                   "Web Application Developer"
resume_contact_email:           "pauleycd@yahoo.com"
resume_header_contact_info: "Solebury, PA | Google Voice: +1 267-714-8647 | pauleyc@yahoo.com"
resume_header_intro: "<p>Experienced application developer seeks interesting project.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/chrispauley/resume"
  resume_twitter_url:           "http://twitter.com/chrisp18938"
  resume_dribbble_url:          "https://dribbble.com/chrisp18938"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/christopherpauley"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://chrispauley.github.io/resume"
  resume_dockerhub_url:         "https://hub.docker.com/u/chrispauley/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
